[build]
  publish = "./"
  functions = "netlify/functions"
  command = "node netlify/inject-env.js"

[dev]
  publish = "./"
  functions = "netlify/functions"
  port = 8888
  autoLaunch = true 